################################
#                              #
#  ADVANCEDRX MOCON PROJECT    #
#     AUTOMATION SCRIPT        #
#         v3.0 (FINAL)         #
#      Author: Marcus Noel     #
################################
#
# WHAT THIS SCRIPT DOES:
#   Watches a folder for new .PRN files generated by the MOCON Automatic
#   Balance Analysis System. When one appears, it parses the file and
#   produces a formatted PDF report, then saves it to the output directory.
#
# DEPENDENCIES (install once):
#   pip install reportlab watchdog
#
# HOW TO RUN:
#   python mocon_converter.py
#   Press Ctrl+C to stop watching.
#
# FILES NEEDED ALONGSIDE THIS SCRIPT:
#   logo.png  — company logo displayed top-right on every page (optional)
#

# ── Standard library ──────────────────────────────────────────────────────────
import os
import re
import time
import errno
from functools import partial

# ── Third-party: file system watching ─────────────────────────────────────────
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# ── Third-party: PDF generation ───────────────────────────────────────────────
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate,   # handles page layout and automatic pagination
    Paragraph,           # styled text block
    Spacer,              # vertical whitespace
    Table,               # grid/table element
    TableStyle,          # styling rules applied to a Table
    KeepTogether,        # prevents a group of elements from splitting across pages
    HRFlowable,          # horizontal rule / divider line
)


# =============================================================================
#  CONFIGURATION
#  Change these two paths to match your environment.
# =============================================================================
WATCH_DIRECTORY  = r"C:\Users\client27\Desktop\Converter"
OUTPUT_DIRECTORY = r"\\server01\DATA\Completed Formula Worksheets\Bulk Processing Batches - QA Sheets"

# Path to the company logo file, relative to wherever you run this script.
# If the file doesn't exist the logo is simply skipped with no error.
LOGO_PATH = "logo.png"

# How many weight values to show per row in the weight range tables.
WEIGHT_COLS = 10

# Small weight tables with this many rows or fewer are kept together with their
# section header so the header never gets orphaned alone at the bottom of a page.
WEIGHT_ROW_KEEP_THRESHOLD = 6

# Number of blank handwriting lines in the "Reweigh of Rejected Caps Weights" box.
REWEIGH_BLANK_LINES = 10


# =============================================================================
#  COLOUR PALETTE  —  Clean two-colour brand system
#  Navy + Gold only. Everything else is white or light grey.
# =============================================================================
COLOR_NAVY         = colors.HexColor("#1A3E99")   # primary — all section headers
COLOR_GOLD         = colors.HexColor("#F5A800")   # accent — key highlights only
COLOR_ROW_ALT      = colors.HexColor("#F7F9FC")   # alternating row — very subtle
COLOR_BORDER       = colors.HexColor("#D1D9E6")   # table grid lines
COLOR_LABEL_BG     = colors.HexColor("#EEF2FA")   # label column background
COLOR_TEXT_DARK    = colors.HexColor("#1A2B4A")   # primary body text
COLOR_TEXT_MID     = colors.HexColor("#4B5C7E")   # secondary / label text
COLOR_REJECT_BG    = colors.HexColor("#FFF0F0")   # reject zone — very subtle
COLOR_ACCEPT_BG    = colors.HexColor("#F0FFF4")   # accept zone — very subtle
COLOR_WHITE        = colors.white
COLOR_BLACK        = colors.HexColor("#1A2B4A")
# Aliases so existing references keep working
COLOR_DARK_GREY    = COLOR_NAVY
COLOR_LIGHT_GREY   = COLOR_ROW_ALT
COLOR_MID_GREY     = COLOR_ROW_ALT
COLOR_BEIGE        = COLOR_ROW_ALT
COLOR_PASTEL_BLUE  = COLOR_NAVY
COLOR_GOLD_LIGHT   = colors.HexColor("#FFFBF0")
COLOR_SLATE        = COLOR_TEXT_MID
COLOR_SLATE_LIGHT  = COLOR_ROW_ALT
COLOR_BLUE         = COLOR_NAVY
COLOR_BLUE_LIGHT   = COLOR_LABEL_BG
COLOR_NAVY_DARK    = COLOR_NAVY
COLOR_REJECT_RED   = COLOR_REJECT_BG
COLOR_ACCEPT_GREEN = COLOR_ACCEPT_BG
COLOR_REJECT_TEXT  = colors.HexColor("#8B1A1A")
COLOR_ACCEPT_TEXT  = colors.HexColor("#1A5C2A")


# =============================================================================
#  PAGE LAYOUT CONSTANTS
#  All measurements are in ReportLab internal points (72 points = 1 inch).
# =============================================================================
PAGE_W, PAGE_H = letter                          # 612 x 792 pt  (8.5" x 11")
L_MARGIN = R_MARGIN = T_MARGIN = B_MARGIN = 0.75 * inch
CONTENT_W = PAGE_W - L_MARGIN - R_MARGIN        # usable width between margins


# =============================================================================
#  REGEX: REPEATED PAGE HEADER PATTERN
#  The MOCON system reprints these four lines at every page break in the PRN.
#  We strip them during parsing so they don't pollute any data section.
# =============================================================================
PAGE_HEADER_RE = re.compile(
    r"^("
    r"MOCON Automatic Balance Analysis System"
    r"|Report includes only data from module"
    r"|Date:\s*\d{2}/\d{2}/\d{2}"
    r"|Time:\s*\d{2}:\d{2}(?::\d{2})?"
    r")$"
)


# =============================================================================
#  FILE ACCESS HELPER
# =============================================================================
def wait_for_file_access(file_path, timeout=10, interval=0.5):
    """
    Try to open and read a file, retrying if it is locked (e.g. still being
    written by MOCON). Raises TimeoutError if the file cannot be read within
    the timeout window.

    Args:
        file_path: Full path to the PRN file.
        timeout:   Maximum seconds to wait before giving up.
        interval:  Seconds to wait between retries.
    """
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            # latin-1 handles the extended ASCII box-drawing characters
            # that MOCON uses for its ASCII table borders (e.g. xc4, xb3).
            with open(file_path, "r", encoding="latin-1") as fh:
                return fh.readlines()
        except IOError as exc:
            if exc.errno == errno.EACCES:
                time.sleep(interval)   # file locked — wait and retry
            else:
                raise                  # any other error — propagate immediately
    raise TimeoutError(f"Could not access {file_path} after {timeout}s")


# =============================================================================
#  STAT VALUE SPLITTER
#  PRN stats are stored as a single string, e.g. "665.66 mg   101.16% of target".
#  This splits them into two separate columns for the Statistical Summary table.
# =============================================================================
def split_stat(raw_val):
    """
    Split a stat string into (left_column, right_column).

    Examples:
        "665.66 mg   101.16% of target"  ->  ("665.66 mg", "101.16% of target")
        "9.3 mg   1.40% Rel Std Dev"     ->  ("9.3 mg",    "1.40% Rel Std Dev")

    Returns (raw_val, "") if the expected format is not found.
    """
    m = re.match(r"([\d.]+ mg)\s+(.*)", raw_val)
    if m:
        return m.group(1), m.group(2)
    return raw_val, ""


# =============================================================================
#  PRN PARSER
#  Reads the raw PRN file and extracts all structured data into a dict.
# =============================================================================
def parse_prn(file_path):
    """
    Parse a MOCON .PRN file into structured data.

    DESIGN PHILOSOPHY — future-proof and character-agnostic:
      MOCON firmware versions differ in which box-drawing characters, pipe
      symbols, arrow styles, and separators they use. This parser NEVER relies
      on specific non-ASCII characters or punctuation. Instead it:
        1. Strips ALL non-printable / non-ASCII bytes up front on every line
        2. Anchors every regex on stable English keywords and numeric patterns
        3. Uses broad wildcards between keywords so surrounding decoration
           is completely irrelevant — any future MOCON firmware will still work
    """
    raw = wait_for_file_access(file_path)

    # ── Step 1: normalise every line ─────────────────────────────────────────
    # Replace form-feeds and ALL non-ASCII bytes with a plain space.
    # This neutralises every box-drawing char, pipe, arrow, and control code
    # regardless of which MOCON firmware version produced the file.
    cleaned = []
    for raw_line in raw:
        line = raw_line.replace("\x0c", "")
        line = re.sub(r"[^\x20-\x7E]", " ", line)
        line = line.rstrip("\n\r")
        if not PAGE_HEADER_RE.match(line.strip()):
            cleaned.append(line)

    full_text = "\n".join(cleaned)

    # ── Step 2: header fields ─────────────────────────────────────────────────
    fields = {}

    # Test#, Date, Time from the raw (uncleaned) first lines
    for raw_line in raw[:5]:
        m = re.search(r"Test#:\s*(\S+)", raw_line)
        if m:
            fields["Test#"] = m.group(1)
            break

    for raw_line in raw[:10]:
        m = re.search(r"Date:\s*(\d{2}/\d{2}/\d{2})", raw_line)
        if m:
            fields["Date"] = m.group(1)
        m = re.search(r"Time:\s*(\d{2}:\d{2}(?::\d{2})?)", raw_line)
        if m:
            fields["Time"] = m.group(1)

    # Generic "Key: Value" extraction from cleaned lines
    for line in cleaned:
        stripped = line.strip()
        m = re.match(r"^([A-Za-z][A-Za-z0-9 #/%]+?):\s*(.*)$", stripped)
        if m:
            key = m.group(1).strip()
            val = m.group(2).strip().strip("*").strip()
            if key not in fields:
                fields[key] = val if val else "(Not Provided)"

    for key in (
        "Test#", "Date", "Time",
        "Product Name", "Product Code", "Batch Number",
        "Machine Number", "Container/Bin",
        "Assay", "Target", "Sort %", "Shell Weight",
    ):
        fields.setdefault(key, "(Not Provided)")

    # ── Step 3: sort analysis ─────────────────────────────────────────────────
    # After non-ASCII stripping the line is always:
    #   Reject [decoration] NNN.N Accept Range NNN.N [decoration] Reject
    # \D{0,15}? skips any arrows, dashes, pipes, spaces between Reject and number
    sort_analysis = None

    sa_header = re.search(
        r"Reject\s+\D{0,15}?([\d.]+)\s+Accept Range\s+([\d.]+)",
        full_text, re.IGNORECASE
    )

    # Counts line always has exactly three NNN/NNN patterns — find the first
    # line in the file that matches this shape
    sa_counts = None
    for line in cleaned:
        matches = re.findall(r"(\d+/\d+)", line)
        if len(matches) == 3:
            sa_counts = matches
            break

    if sa_header and sa_counts:
        sort_analysis = {
            "reject_low":  sa_header.group(1),
            "reject_high": sa_header.group(2),
            "counts_low":  sa_counts[0],
            "counts_mid":  sa_counts[1],
            "counts_high": sa_counts[2],
        }

    # ── Step 4: statistical summary ───────────────────────────────────────────
    # Captures everything after the mg value so any future unit wording works
    stats = {}
    stat_patterns = {
        "Samples": r"Samples:\s*(\d+)",
        "Mean":    r"Mean:\s*([\d.]+ mg\s+.+)",
        "Maximum": r"Maximum:\s*([\d.]+ mg\s+.+)",
        "Minimum": r"Minimum:\s*([\d.]+ mg\s+.+)",
        "Max Dev": r"Max Dev:\s*([\d.]+ mg\s+.+)",
        "Std Dev": r"Std Dev:\s*([\d.]+ mg\s+.+)",
    }
    for stat_key, pattern in stat_patterns.items():
        m = re.search(pattern, full_text)
        if m:
            stats[stat_key] = m.group(1).strip()

    # ── Step 5: weight ranges ─────────────────────────────────────────────────
    # "WEIGHTS IN <n> RANGE" is stable across all known firmware versions
    weight_ranges = []
    parts = re.split(r"WEIGHTS IN (.*?) RANGE", full_text)
    for i in range(1, len(parts), 2):
        range_name = parts[i].strip()
        data_block = parts[i + 1] if i + 1 < len(parts) else ""
        data_lines = [
            ln.strip() for ln in data_block.splitlines()
            if ln.strip() and not re.match(r"^-{5,}$", ln.strip())
        ]
        weight_ranges.append((range_name, data_lines))

    return {
        "fields":        fields,
        "sort_analysis": sort_analysis,
        "stats":         stats,
        "weight_ranges": weight_ranges,
    }


# =============================================================================
#  TABLE FACTORY
#  Builds a standard two-tone table: coloured header row + alternating data rows.
#  Used for Report Details, Product Information, and Analysis Data sections.
# =============================================================================
def make_table(data, col_widths, header_bg=None, span_header=True):
    """
    Standard info table: navy header row, label col in light grey,
    value col in white with subtle alternating rows. Clean and minimal.
    """
    header_bg = header_bg or COLOR_NAVY
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        # Header row — navy, white text, gold underline
        ("BACKGROUND",    (0, 0), (-1, 0), COLOR_NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), COLOR_WHITE),
        ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 10),
        ("TOPPADDING",    (0, 0), (-1, 0), 7),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
        ("LINEBELOW",     (0, 0), (-1, 0), 2, COLOR_GOLD),
        # Label column — very light blue-grey tint, bold navy text, left-aligned
        ("BACKGROUND",    (0, 1), (0, -1), COLOR_LABEL_BG),
        ("TEXTCOLOR",     (0, 1), (0, -1), COLOR_TEXT_DARK),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 1), (0, -1), 9),
        ("ALIGN",         (0, 1), (0, -1), "LEFT"),
        ("LEFTPADDING",   (0, 1), (0, -1), 10),
        # Value column — white / off-white alternating, left-aligned
        ("ROWBACKGROUNDS", (1, 1), (1, -1), [COLOR_WHITE, COLOR_ROW_ALT]),
        ("TEXTCOLOR",      (1, 1), (1, -1), COLOR_TEXT_DARK),
        ("FONTNAME",       (1, 1), (1, -1), "Helvetica"),
        ("FONTSIZE",       (1, 1), (1, -1), 9),
        ("ALIGN",          (1, 1), (1, -1), "LEFT"),
        ("LEFTPADDING",    (1, 1), (1, -1), 10),
        # All cells
        ("TOPPADDING",    (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("GRID",          (0, 0), (-1, -1), 0.4, COLOR_BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]
    if span_header:
        style_cmds.append(("SPAN", (0, 0), (-1, 0)))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


# =============================================================================
#  PAGE CALLBACK  — navy banner + gold rule footer on every page
# =============================================================================
def on_page(canvas, doc, logo_path=None, fields=None):
    """
    Every page gets:
      - A clean navy banner at the top (taller on page 1, slim on page 2+)
      - A single gold rule at the bottom with minimal metadata + page number
    """
    canvas.saveState()
    fields = fields or {}

    BANNER_H  = 48   # page 1 banner height
    RUNNING_H = 20   # pages 2+ slim header height

    if doc.page == 1:
        # Navy banner
        canvas.setFillColor(COLOR_NAVY)
        canvas.rect(0, PAGE_H - BANNER_H, PAGE_W, BANNER_H, fill=1, stroke=0)
        # Thin gold stripe along top
        canvas.setFillColor(COLOR_GOLD)
        canvas.rect(0, PAGE_H - 3, PAGE_W, 3, fill=1, stroke=0)
        # Title
        canvas.setFillColor(COLOR_WHITE)
        canvas.setFont("Helvetica-Bold", 14)
        canvas.drawString(L_MARGIN, PAGE_H - 26,
            "MOCON Automatic Balance Analysis System")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#B8CCEE"))
        canvas.drawString(L_MARGIN, PAGE_H - 40, "AdvancedRx — Quality Control Report")
        # Logo
        if logo_path and os.path.exists(logo_path):
            canvas.drawImage(logo_path,
                PAGE_W - R_MARGIN - 85, PAGE_H - BANNER_H + 5,
                width=80, height=38,
                preserveAspectRatio=True, mask="auto")
    else:
        # Slim running header on pages 2+
        canvas.setFillColor(COLOR_NAVY)
        canvas.rect(0, PAGE_H - RUNNING_H, PAGE_W, RUNNING_H, fill=1, stroke=0)
        canvas.setFillColor(COLOR_GOLD)
        canvas.rect(0, PAGE_H - 3, PAGE_W, 3, fill=1, stroke=0)
        canvas.setFillColor(COLOR_WHITE)
        canvas.setFont("Helvetica-Bold", 7.5)
        canvas.drawString(L_MARGIN, PAGE_H - 13,
            "MOCON Automatic Balance Analysis System — AdvancedRx")
        canvas.setFont("Helvetica", 7.5)
        canvas.drawRightString(PAGE_W - R_MARGIN, PAGE_H - 13,
            f"{fields.get('Product Name','')}  |  Batch: {fields.get('Batch Number','')}")

    # Gold rule footer — one line, no clutter
    canvas.setStrokeColor(COLOR_GOLD)
    canvas.setLineWidth(1.5)
    canvas.line(L_MARGIN, B_MARGIN - 5, PAGE_W - R_MARGIN, B_MARGIN - 5)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(COLOR_TEXT_MID)
    canvas.drawString(L_MARGIN, B_MARGIN - 15,
        f"Test #: {fields.get('Test#','')}  |  "
        f"Date: {fields.get('Date','')}  |  "
        f"Batch: {fields.get('Batch Number','')}")
    canvas.drawRightString(PAGE_W - R_MARGIN, B_MARGIN - 15,
        f"Page {doc.page}")

    canvas.restoreState()


# =============================================================================
#  PARAGRAPH STYLES
#  Defined centrally so fonts and sizes stay consistent throughout the document.
# =============================================================================
def get_styles():
    """Return a dict of named ParagraphStyle objects used across the PDF."""
    base = getSampleStyleSheet()
    return {
        # Large centred title at the top of the document
        "title": ParagraphStyle(
            "DocTitle",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            textColor=COLOR_NAVY,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        # Small left-aligned label — used for warnings / fallback messages
        "warning": ParagraphStyle(
            "Warning",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=COLOR_BLACK,
            alignment=TA_LEFT,
        ),
    }


# =============================================================================
#  MAIN PDF BUILDER
#  Calls parse_prn(), then assembles a ReportLab "story" (list of flowables)
#  and writes the finished PDF to OUTPUT_DIRECTORY.
# =============================================================================
def create_pdf_from_prn(prn_file):
    """Convert a single .PRN file to a formatted PDF and save it."""
    base_filename = os.path.splitext(os.path.basename(prn_file))[0]
    pdf_file = os.path.join(OUTPUT_DIRECTORY, base_filename + ".pdf")

    try:
        parsed = parse_prn(prn_file)
    except Exception as exc:
        print(f"  [ERROR] Could not parse {prn_file}: {exc}")
        return

    fields        = parsed["fields"]
    sort_analysis = parsed["sort_analysis"]
    stats         = parsed["stats"]
    weight_ranges = parsed["weight_ranges"]

    # SimpleDocTemplate handles automatic page breaks and margin application.
    # Extra top/bottom margin leaves room for the logo and footer respectively.
    doc = SimpleDocTemplate(
        pdf_file,
        pagesize=letter,
        leftMargin=L_MARGIN,
        rightMargin=R_MARGIN,
        topMargin=T_MARGIN + 20,
        bottomMargin=B_MARGIN + 20,
    )

    styles = get_styles()
    story  = []   # list of flowables built up section by section


    # =========================================================================
    #  SECTION 1: DOCUMENT TITLE
    # =========================================================================
    # Banner is drawn by on_page() — just clear it with a spacer
    story.append(Spacer(1, 6))


    # =========================================================================
    #  SECTION 2: REPORT DETAILS  (Test #, Date, Time)
    # =========================================================================
    report_data = [
        ["Report Details"],   # header — spans all 3 columns via make_table
        [
            f"Test #:  {fields['Test#']}",
            f"Date:  {fields['Date']}",
            f"Time:  {fields['Time']}",
        ],
    ]
    report_tbl = Table(report_data[1:], colWidths=[CONTENT_W/3]*3)
    report_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0),(-1,-1), COLOR_NAVY),
        ("TEXTCOLOR",    (0,0),(-1,-1), COLOR_WHITE),
        ("FONTNAME",     (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0),(-1,-1), 9),
        ("ALIGN",        (0,0),(-1,-1), "CENTER"),
        ("TOPPADDING",   (0,0),(-1,-1), 7),
        ("BOTTOMPADDING",(0,0),(-1,-1), 7),
        ("LINEAFTER",    (0,0),(1,-1),  1, COLOR_GOLD),
        ("LINEABOVE",    (0,0),(-1, 0), 2, COLOR_GOLD),
    ]))
    story.append(KeepTogether([report_tbl]))
    story.append(Spacer(1, 10))


    # =========================================================================
    #  SECTION 3: PRODUCT INFORMATION
    #  35% label column / 65% value column gives labels room without wasting space.
    # =========================================================================
    prod_data = [
        ["Product Information"],
        ["Product Name",   fields.get("Product Name",   "(Not Provided)")],
        ["Product Code",   fields.get("Product Code",   "(Not Provided)")],
        ["Batch Number",   fields.get("Batch Number",   "(Not Provided)")],
        ["Machine Number", fields.get("Machine Number", "(Not Provided)")],
        ["Container/Bin",  fields.get("Container/Bin",  "(Not Provided)")],
    ]
    prod_tbl = make_table(
        prod_data,
        col_widths=[CONTENT_W * 0.32, CONTENT_W * 0.68],
    )
    story.append(KeepTogether([prod_tbl]))
    story.append(Spacer(1, 8))


    # =========================================================================
    #  SECTION 4: ANALYSIS DATA
    # =========================================================================
    analysis_data = [
        ["Analysis Data"],
        ["Assay",        fields.get("Assay",        "(Not Provided)")],
        ["Target",       fields.get("Target",       "(Not Provided)")],
        ["Sort %",       fields.get("Sort %",       "(Not Provided)")],
        ["Shell Weight", fields.get("Shell Weight", "(Not Provided)")],
    ]
    analysis_tbl = make_table(
        analysis_data,
        col_widths=[CONTENT_W * 0.32, CONTENT_W * 0.68],
    )
    story.append(KeepTogether([analysis_tbl]))
    story.append(Spacer(1, 10))


    # =========================================================================
    #  SECTION 5: SORT ANALYSIS BASED ON TARGET
    #  Three-column layout: reject (red) | accept (green) | reject (red).
    #  Shows the threshold values and the actual counts from the run.
    #  Falls back to a warning paragraph if the parser found no data.
    # =========================================================================
    if sort_analysis:
        sa = sort_analysis
        col_w = CONTENT_W / 3

        sort_data = [
            ["Sort Analysis Based on Target"],   # title — spans all 3 cols
            [
                f"Reject (<) {sa['reject_low']}",    # below lower threshold
                "Accepted Range",
                f"{sa['reject_high']} (>) Reject",   # above upper threshold
            ],
            [
                sa["counts_low"],    # rejected count / total (low side)
                sa["counts_mid"],    # accepted count / total
                sa["counts_high"],   # rejected count / total (high side)
            ],
        ]
        sort_tbl = Table(sort_data, colWidths=[col_w] * 3)
        sort_tbl.setStyle(TableStyle([
            # Title row
            ("SPAN",         (0, 0), (-1, 0)),
            ("BACKGROUND",   (0, 0), (-1, 0), COLOR_NAVY),
            ("TEXTCOLOR",    (0, 0), (-1, 0), COLOR_WHITE),
            ("ALIGN",        (0, 0), (-1, 0), "CENTER"),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, 0), 11),
            ("TOPPADDING",   (0, 0), (-1, 0), 6),
            ("BOTTOMPADDING",(0, 0), (-1, 0), 6),
            # Label row
            ("BACKGROUND",   (0, 1), (0, 1), COLOR_REJECT_RED),
            ("BACKGROUND",   (1, 1), (1, 1), COLOR_ACCEPT_GREEN),
            ("BACKGROUND",   (2, 1), (2, 1), COLOR_REJECT_RED),
            ("FONTNAME",     (0, 1), (-1, 1), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 1), (-1, 1), 9),
            ("ALIGN",        (0, 1), (-1, 1), "CENTER"),
            ("TOPPADDING",   (0, 1), (-1, 1), 5),
            ("BOTTOMPADDING",(0, 1), (-1, 1), 5),
            # Counts row
            ("BACKGROUND",   (0, 2), (0, 2), COLOR_REJECT_RED),
            ("BACKGROUND",   (1, 2), (1, 2), COLOR_ACCEPT_GREEN),
            ("BACKGROUND",   (2, 2), (2, 2), COLOR_REJECT_RED),
            ("FONTNAME",     (0, 2), (-1, 2), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 2), (-1, 2), 10),
            ("ALIGN",        (0, 2), (-1, 2), "CENTER"),
            ("TOPPADDING",   (0, 2), (-1, 2), 5),
            ("BOTTOMPADDING",(0, 2), (-1, 2), 5),
            # All cells
            ("GRID",     (0,0),(-1,-1), 0.4, COLOR_BORDER),
            ("VALIGN",   (0,0),(-1,-1), "MIDDLE"),
            ("LINEBELOW",(0,0),(-1, 0), 2,   COLOR_GOLD),
            ("TEXTCOLOR",(0,1),(0,1), COLOR_REJECT_TEXT),
            ("TEXTCOLOR",(1,1),(1,1), COLOR_ACCEPT_TEXT),
            ("TEXTCOLOR",(2,1),(2,1), COLOR_REJECT_TEXT),
            ("TEXTCOLOR",(0,2),(0,2), COLOR_REJECT_TEXT),
            ("TEXTCOLOR",(1,2),(1,2), COLOR_ACCEPT_TEXT),
            ("TEXTCOLOR",(2,2),(2,2), COLOR_REJECT_TEXT),
        ]))
        story.append(KeepTogether([sort_tbl]))
        story.append(Spacer(1, 10))
    else:
        story.append(Paragraph(
            "No sort analysis data found in this file.", styles["warning"]
        ))
        story.append(Spacer(1, 6))


    # =========================================================================
    #  SECTION 6: REWEIGH OF REJECTED CAPS RESULTS
    #  Manual fill-in box — label at the top, generous space below for writing.
    # =========================================================================
    reweigh_result_tbl = Table(
        [["Reweigh of Rejected Caps Results:"]],
        colWidths=[CONTENT_W]
    )
    reweigh_result_tbl.setStyle(TableStyle([
        ("BOX",          (0,0),(-1,-1), 1,   COLOR_NAVY),
        ("LINEABOVE",    (0,0),(-1, 0), 2.5, COLOR_GOLD),
        ("BACKGROUND",   (0,0),(-1,-1), COLOR_LABEL_BG),
        ("TEXTCOLOR",    (0,0),(-1,-1), COLOR_TEXT_DARK),
        ("FONTNAME",     (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0),(-1,-1), 10),
        ("ALIGN",        (0,0),(-1,-1), "LEFT"),
        ("LEFTPADDING",  (0,0),(-1,-1), 10),
        ("TOPPADDING",   (0,0),(-1,-1), 7),
        ("BOTTOMPADDING",(0,0),(-1,-1), 22),
    ]))
    story.append(KeepTogether([reweigh_result_tbl]))
    story.append(Spacer(1, 10))


    # =========================================================================
    #  SECTION 7: STATISTICAL SUMMARY
    #  Two columns exactly 50/50 so the vertical divider sits dead centre.
    #  Left column: label + mg value.  Right column: percentage of target.
    # =========================================================================
    stats_rows = [
        ["Statistical Summary", ""],                                   # title row
        [f"Samples: {stats.get('Samples', '(Not Provided)')}", ""],    # bold full-width row
    ]
    for label in ("Mean", "Maximum", "Minimum", "Max Dev", "Std Dev"):
        raw = stats.get(label)
        if raw:
            left, right = split_stat(raw)
            stats_rows.append([f"{label}:  {left}", right])

    stats_tbl = Table(
        stats_rows,
        colWidths=[CONTENT_W * 0.5, CONTENT_W * 0.5],   # exact 50/50 split
    )
    stats_tbl.setStyle(TableStyle([
        # Title row
        ("SPAN",          (0, 0), (-1, 0)),
        ("BACKGROUND",    (0, 0), (-1, 0), COLOR_MID_GREY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), COLOR_BLACK),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 11),
        ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        # Samples row — spans both columns, bold
        ("SPAN",          (0, 1), (-1, 1)),
        ("BACKGROUND",    (0, 1), (-1, 1), COLOR_LIGHT_GREY),
        ("FONTNAME",      (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 1), (-1, 1), 10),
        ("ALIGN",         (0, 1), (-1, 1), "CENTER"),
        ("TOPPADDING",    (0, 1), (-1, 1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 5),
        # Data rows
        ("ROWBACKGROUNDS", (0, 2), (-1, -1), [COLOR_LIGHT_GREY, COLOR_WHITE]),
        ("FONTNAME",       (0, 2), (-1, -1), "Helvetica"),
        ("FONTSIZE",       (0, 2), (-1, -1), 9),
        ("ALIGN",          (0, 2), (-1, -1), "LEFT"),
        ("LEFTPADDING",    (0, 0), (-1, -1), 8),
        ("TOPPADDING",     (0, 2), (-1, -1), 4),
        ("BOTTOMPADDING",  (0, 2), (-1, -1), 4),
        # All cells
        ("GRID",      (0,0),(-1,-1), 0.4, COLOR_BORDER),
        ("VALIGN",    (0,0),(-1,-1), "MIDDLE"),
        ("LINEBELOW", (0,0),(-1, 0), 2,   COLOR_GOLD),
        ("BACKGROUND",(0,1),(-1, 1), COLOR_GOLD),
        ("TEXTCOLOR", (0,1),(-1, 1), COLOR_NAVY),
    ]))
    story.append(KeepTogether([stats_tbl]))
    story.append(Spacer(1, 10))


    # =========================================================================
    #  SECTION 8: WEIGHT RANGE TABLES  (-T3 through +T3)
    #
    #  PAGINATION STRATEGY:
    #  - Empty ranges: title + "No data" merged into one table with splitByRow=0
    #    AND wrapped in KeepTogether — two layers so they never separate.
    #  - Small tables (<= WEIGHT_ROW_KEEP_THRESHOLD rows): KeepTogether with
    #    the title bar so neither is orphaned alone at the bottom of a page.
    #  - Large tables: title added separately, table flows freely across pages.
    #    splitByRow=1 allows row-level breaks so large datasets paginate cleanly.
    # =========================================================================
    for range_name, data_lines in weight_ranges:

        # Parse (count, weight) pairs from each raw data line.
        # Raw lines look like: "1  645.1    1  646.6    1  647.2 ..."
        # We discard counts and keep only the weight values.
        entries = []
        for dl in data_lines:
            pairs = re.findall(r"(\d+)\s+([\d.]+)", dl)
            entries.extend(pairs)

        weight_values = [wt for (_, wt) in entries]

        # -----------------------------------------------------------------
        # Empty range — merge title + "No data" into a single unsplittable table
        # -----------------------------------------------------------------
        if not weight_values:
            combined_empty = Table(
                [
                    [f"Weights in {range_name} Range"],
                    ["No data in this range"],
                ],
                colWidths=[CONTENT_W],
                splitByRow=0,   # Platypus cannot split this table at the row level
            )
            combined_empty.setStyle(TableStyle([
                # Title row
                ("BACKGROUND",    (0,0),(-1,0), COLOR_NAVY),
                ("TEXTCOLOR",     (0,0),(-1,0), COLOR_WHITE),
                ("ALIGN",         (0,0),(-1,0), "LEFT"),
                ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0),(-1,0), 9),
                ("TOPPADDING",    (0,0),(-1,0), 5),
                ("BOTTOMPADDING", (0,0),(-1,0), 5),
                ("LEFTPADDING",   (0,0),(-1,0), 10),
                ("LINEBELOW",     (0,0),(-1,0), 1.5, COLOR_GOLD),
                # "No data" row
                ("BACKGROUND",    (0,1),(-1,1), COLOR_ROW_ALT),
                ("TEXTCOLOR",     (0,1),(-1,1), COLOR_TEXT_MID),
                ("ALIGN",         (0,1),(-1,1), "CENTER"),
                ("FONTNAME",      (0,1),(-1,1), "Helvetica-Oblique"),
                ("FONTSIZE",      (0,1),(-1,1), 9),
                ("TOPPADDING",    (0,1),(-1,1), 5),
                ("BOTTOMPADDING", (0,1),(-1,1), 5),
                ("GRID",          (0,0),(-1,-1), 0.4, COLOR_BORDER),
            ]))
            story.append(KeepTogether([combined_empty]))   # second layer of protection
            story.append(Spacer(1, 6))
            continue

        # -----------------------------------------------------------------
        # Populated range — build the section title bar and weight data table
        # -----------------------------------------------------------------

        # Section title bar (separate flowable so large tables can flow freely
        # across pages without the title forcing everything onto a new page)
        title_tbl = Table(
            [[f"Weights in {range_name} Range"]],
            colWidths=[CONTENT_W]
        )
        title_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), COLOR_NAVY),
            ("TEXTCOLOR",     (0,0),(-1,-1), COLOR_WHITE),
            ("ALIGN",         (0,0),(-1,-1), "LEFT"),
            ("FONTNAME",      (0,0),(-1,-1), "Helvetica-Bold"),
            ("FONTSIZE",      (0,0),(-1,-1), 9),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 10),
            ("LINEBELOW",     (0,0),(-1,-1), 1.5, COLOR_GOLD),
        ]))

        # Pack weight values into rows of WEIGHT_COLS values each.
        # Pad the last row with empty strings to complete the grid.
        data_rows = []
        row = []
        for wt in weight_values:
            row.append(wt)
            if len(row) == WEIGHT_COLS:
                data_rows.append(row)
                row = []
        if row:
            while len(row) < WEIGHT_COLS:
                row.append("")
            data_rows.append(row)

        num_data_rows = len(data_rows)
        col_w = CONTENT_W / WEIGHT_COLS

        weight_tbl = Table(
            data_rows,
            colWidths=[col_w] * WEIGHT_COLS,
            # Small tables: never split (whole table moves to next page as a unit)
            # Large tables: allow row-level breaks so data paginates naturally
            splitByRow=0 if num_data_rows <= WEIGHT_ROW_KEEP_THRESHOLD else 1,
        )
        weight_tbl.setStyle(TableStyle([
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [COLOR_WHITE, COLOR_ROW_ALT]),
            ("FONTNAME",       (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",       (0, 0), (-1, -1), 8),
            ("ALIGN",          (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING",     (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 3),
            ("GRID",           (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ]))

        # Small table: glue title + data together so neither is orphaned
        # Large table: title separate, data flows freely
        if num_data_rows <= WEIGHT_ROW_KEEP_THRESHOLD:
            story.append(KeepTogether([title_tbl, weight_tbl]))
        else:
            story.append(title_tbl)
            story.append(weight_tbl)

        story.append(Spacer(1, 8))


    # =========================================================================
    #  SECTION 9: REWEIGH OF REJECTED CAPS WEIGHTS
    #  Manual fill-in box with 10 blank lines for handwritten weight entries.
    #  Outer border only — no internal grid lines.
    # =========================================================================
    reweigh_wt_rows = [["Reweigh of Rejected Caps Weights:"]]
    for _ in range(REWEIGH_BLANK_LINES):
        reweigh_wt_rows.append([""])   # blank lines for handwriting

    reweigh_wt_tbl = Table(reweigh_wt_rows, colWidths=[CONTENT_W])
    reweigh_wt_tbl.setStyle(TableStyle([
        ("BOX",          (0,0),(-1,-1), 1,   COLOR_NAVY),
        ("LINEABOVE",    (0,0),(-1, 0), 2.5, COLOR_GOLD),
        ("BACKGROUND",   (0,0),( 0, 0), COLOR_LABEL_BG),
        ("TEXTCOLOR",    (0,0),( 0, 0), COLOR_TEXT_DARK),
        ("FONTNAME",     (0,0),( 0, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0),(-1,-1), 9),
        ("ALIGN",        (0,0),(-1,-1), "LEFT"),
        ("LEFTPADDING",  (0,0),(-1,-1), 10),
        ("TOPPADDING",   (0,0),(-1,-1), 5),
        ("BOTTOMPADDING",(0,0),(-1,-1), 5),
    ]))
    story.append(KeepTogether([reweigh_wt_tbl]))
    story.append(Spacer(1, 16))


    # =========================================================================
    #  SECTION 10: SIGNATURE LINE
    #  "Reviewed by" left-aligned, "Date Reviewed" right-aligned.
    # =========================================================================
    sign_tbl = Table(
        [["Reviewed by: ________________________",
          "Date Reviewed: ________________________"]],
        colWidths=[CONTENT_W / 2] * 2,
    )
    sign_tbl.setStyle(TableStyle([
        ("FONTNAME",     (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, -1), 10),
        ("ALIGN",        (0, 0), (0, -1), "LEFT"),
        ("ALIGN",        (1, 0), (1, -1), "RIGHT"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
    ]))
    story.append(sign_tbl)


    # =========================================================================
    #  BUILD THE PDF
    #  doc.build() flows the story list through the page template, calling
    #  on_page after each page is rendered to draw the logo and footer.
    #  partial() pre-binds LOGO_PATH since ReportLab's callback is (canvas, doc).
    # =========================================================================
    page_cb = partial(on_page, logo_path=LOGO_PATH, fields=fields)
    doc.build(story, onFirstPage=page_cb, onLaterPages=page_cb)
    print(f"  [OK] PDF written -> {pdf_file}")


# =============================================================================
#  FILE SYSTEM WATCHER
#  Monitors WATCH_DIRECTORY for new .PRN files. When one appears it calls
#  create_pdf_from_prn(), retrying up to 5 times if the file is still locked.
# =============================================================================
class PRNHandler(FileSystemEventHandler):
    """Watchdog event handler — responds to new files in the watch directory."""

    def on_created(self, event):
        """Called by watchdog whenever a new file or folder is created."""
        if event.is_directory:
            return   # ignore folder creation events

        if not event.src_path.upper().endswith(".PRN"):
            return   # ignore non-PRN files (e.g. temp files, logs)

        print(f"\033[92m[EVENT] New PRN file detected: {event.src_path}\033[0m")

        # Retry loop — MOCON may still have the file open when watchdog fires
        for attempt in range(1, 6):
            try:
                create_pdf_from_prn(event.src_path)
                print(f"\033[94m[DONE]  PDF saved to {OUTPUT_DIRECTORY}\033[0m")
                return   # success — exit the retry loop
            except PermissionError:
                print(f"  [RETRY] Attempt {attempt}/5 — file still locked, waiting 2s...")
                time.sleep(2)
            except Exception as exc:
                print(f"\033[91m[ERROR] {exc}\033[0m")
                return   # unexpected error — stop retrying

        print("\033[91m[FAIL]  Could not process file after 5 attempts.\033[0m")


# =============================================================================
#  ENTRY POINT
# =============================================================================
if __name__ == "__main__":
    # Ensure the output directory exists before starting the watcher
    if not os.path.exists(OUTPUT_DIRECTORY):
        os.makedirs(OUTPUT_DIRECTORY)

    print(f"\033[93mWatching:  {WATCH_DIRECTORY}\033[0m")
    print(f"\033[93mOutput to: {OUTPUT_DIRECTORY}\033[0m")

    observer = Observer()
    observer.schedule(PRNHandler(), WATCH_DIRECTORY, recursive=False)
    observer.start()
    print("\033[92m[READY] Watching for .PRN files. Press Ctrl+C to stop.\033[0m")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
